const express = require('express');
const PDFDocument = require('pdfkit');
const { pool } = require('../db/pool');
const { withTenant } = require('../db/withTenant');

const router = express.Router();

// No session: a parent opens this from an SMS link. Security comes from
// the token being unguessable, not from a login — the same reasoning as
// the M-Pesa callback URL.
router.get('/:token', async (req, res) => {
  const found = await pool.query(
    'SELECT p.id, p.tenant_id FROM payments p WHERE p.receipt_token = $1',
    [req.params.token]
  );
  const row = found.rows[0];
  if (!row) return res.status(404).send('Receipt not found');

  const data = await withTenant(row.tenant_id, (client) =>
    client.query(
      `SELECT p.provider, p.provider_ref, p.amount_minor, p.created_at,
              s.full_name AS student_name, s.admission_no,
              t.name AS school_name
       FROM payments p
       JOIN students s ON s.id = p.student_id
       JOIN tenants t ON t.id = p.tenant_id
       WHERE p.id = $1 AND p.status = 'settled'`,
      [row.id]
    )
  );
  const r = data.rows[0];
  if (!r) return res.status(404).send('Receipt not available');

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="receipt-${r.provider_ref}.pdf"`);
  doc.pipe(res);

  doc.fontSize(20).text(r.school_name);
  doc.fontSize(10).fillColor('#666').text('Payment receipt');
  doc.moveDown(2);

  doc.fillColor('#000').fontSize(11);
  const line = (label, value) => {
    doc.font('Helvetica').fillColor('#666').text(label, { continued: true });
    doc.font('Helvetica-Bold').fillColor('#000').text('   ' + value);
    doc.moveDown(0.4);
  };

  line('Student', r.student_name);
  line('Admission no.', r.admission_no);
  line('Amount', `KES ${(Number(r.amount_minor) / 100).toLocaleString()}`);
  line('Reference', r.provider_ref);
  line('Method', r.provider === 'mpesa' ? 'M-Pesa' : 'Card');
  line('Date', new Date(r.created_at).toLocaleString('en-GB'));

  doc.moveDown(2);
  doc.fontSize(9).fillColor('#999')
     .text('This receipt was generated by EduLevy. Keep it for your records.');

  doc.end();
});

module.exports = router;