CREATE ROLE edulevy_app WITH LOGIN PASSWORD 'Tanzania25*';
GRANT CONNECT ON DATABASE edulevy_db TO edulevy_app;
GRANT USAGE ON SCHEMA public TO edulevy_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO edulevy_app;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO edulevy_app;